id = "forest-cottage-theme"
name = "Forest Cottage"
version = "1.0.0"
schema_version = 1
authors = ["Zephiris Evergreen <z@zephiris.dev>"]
description = "A foresty theme 🍃"
repository = "https://github.com/zphrs/forest-cottage-theme"
